version: 0.2
cache:
  paths:
    - '~/.gradle/caches'
    - '.gradle/'
    - 'build/'
phases:
  install:
    commands:
      - echo "install step running on..."
      - echo "running commit $CODEBUILD_SOURCE_VERSION"
      - apt-get install build-essential
      - echo "install step done!"
  pre_build:
    commands:
      - echo "pre_build step"
      - chmod +x gradlew
  build:
    commands:
      - ./gradlew packageLambda --info --stacktrace
      - ls -lah build/dist
      - aws s3 sync build/dist ${S3_BUCKET_URL}
      - aws lambda update-function-code --function-name $FUNCTION_NAME --s3-bucket $S3_BUCKET --s3-key $S3_KEY
  post_build:
    commands:
      - echo "post_build step"
      - printenv
      - |-
        curl -d "{\"text\": \"Just Build ${CODEBUILD_SOURCE_VERSION} triggered by ${CODEBUILD_INITIATOR} with Status: ${CODEBUILD_BUILD_SUCCEEDING}\"}" ${SLACK_WEBHOOK}