version: 0.2
phases:
  install:
    commands:
      - echo "install step running on..."
      - echo "running commit $CODEBUILD_SOURCE_VERSION"
      - echo "installing build-essential unzip"
      - apt-get install build-essential
      - echo "installing terraform"
      - wget https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
      - unzip terraform_0.11.13_linux_amd64.zip
      - sudo install terraform /usr/local/bin/
      - terraform --version
      - echo "install step done!"
  pre_build:
    commands:
      - echo "pre_build step"
      - chmod +x gradlew
  build:
    commands:
      - ./gradlew packageLambda
      - ls -lah build/dist
      - aws s3 sync build/dist ${S3_BUCKET}
      - terraform.exe apply -input=false
  post_build:
    commands:
      - echo "post_build step"
      - printenv
      - |-
        curl -d "{\"text\": \"Just Build ${CODEBUILD_SOURCE_VERSION} triggered by ${CODEBUILD_INITIATOR} with Status: ${CODEBUILD_BUILD_SUCCEEDING}\"}" ${SLACK_WEBHOOK}